// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'exchange.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'exchange.g.dart';

@freezed
class Exchange with _$Exchange {
  const factory Exchange({

    @JsonKey(name: 'time_last_update_utc')
    required String timeLastUpdateUtc,
    @JsonKey(name: 'conversion_rates')
    required Map<String, dynamic> conversionRates,
  }) = _Exchange;

  factory Exchange.fromJson(Map<String, Object?> json)
  => _$ExchangeFromJson(json);
}